export const icons = {
  edit: require('assets/images/icon_edit.png'),
  add: require('assets/images/icon_add.png'),
  close: require('assets/images/icon_close.png'),
  like: require('assets/images/icon_like.png'),
  dropdown: require('assets/images/icon_dropdown.png'),
  information: require('assets/images/icon_information.png'),
  next: require('assets/images/icon_next.png'),
  back: require('assets/images/icon_back.png'),
  camera: require('assets/images/icon_camera.png'),
  image: require('assets/images/icon_image.png'),
  profile: require('assets/images/icon_profile.png'),
  tape: require('assets/images/icon_tape.png'),
  create: require('assets/images/icon_create.png'),
  chat: require('assets/images/icon_chat.png'),
  setting: require('assets/images/icon_setting.png'),
  more: require('assets/images/icon_more.png'),
  icon_social_1: require('assets/images/icon_social_1.png'),
  icon_social_2: require('assets/images/icon_social_2.png'),
  send: require('assets/images/icon_send.png'),
};

export const images = {
  logo: require('assets/images/logo.png'),
  test: require('assets/images/bag.jpg'),
  authBackground: require('assets/images/authBackground.png'),
  union: require('assets/images/union.png'),
  tip4: require('assets/images/tip4.png'),
  tip3: require('assets/images/tip3.png'),
  tip1: require('assets/images/tip1.png'),
  tip2: require('assets/images/tip2.png'),
  feed1: require('assets/images/feed1.jpg'),
  feed2: require('assets/images/feed2.jpg'),
  gradient: require('assets/images/gradient.png'),
  avatar: require('assets/images/avatar.jpg'),
};
